# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-03 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0002_auto_20180303_1955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite_Table',
            new_name='Favorite',
        ),
    ]
