# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-03 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0003_auto_20180303_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_quotes', to='login_register.Quote'),
        ),
    ]
