# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0006_user_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
