# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 01:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0007_quotemanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuoteManager',
        ),
    ]
